version: "2.0"
services:
 vue-new-app:
  build:
   context: .
   dockerfile: ./Dockerfile
  volumes:
  -   ./src:/usr/src/app/src
  -   ./public:/usr/src/app/public
  -   ./vue.config.js:/usr/src/app/vue.config.js
  ports:
  -  "80:8080"
  -  "3000:3000"
